exports.commonTerms = [
    'I am batman', 
    'ace the bat-hound', 
    'alfred pennyworth', 
    'anarky', 
    'arkham asylum', 
    'arkham knight', 
    'arkham', 
    'azrael', 
    'bane', 
    'bat family', 
    'bat shark repellent', 
    'bat signal', 
    'bat-cave', 
    'bat-mite', 
    'batarang', 
    'batgirl', 
    'batman beyond', 
    'batman', 
    'batmobile', 
    'batwing', 
    'batwoman', 
    'black canary', 
    'black mask', 
    'blüdhaven', 
    'brave and the bold', 
    'bruce wayne', 
    'burnside', 
    'calendar man', 
    'cape', 
    'caped crusader', 
    'catwoman', 
    'clayface', 
    'clock king', 
    'commissioner gordon', 
    'condiment king', 
    'court of owls', 
    'cowl', 
    'criminally insane', 
    'deadshot', 
    'deathstroke', 
    'falcone', 
    'firefly', 
    'flying graysons', 
    'gadgets', 
    'gcpd', 
    'gotham', 
    'harley quinn', 
    'harvey bullock', 
    'hugo strange', 
    'huntress', 
    'hush', 
    'joe chill', 
    'joker', 
    'justice league', 
    'justice', 
    'killer croc', 
    'killer moth', 
    'kite man', 
    'kite-man', 
    'lazarus pit', 
    'lucius fox', 
    'mad hatter', 
    'man-bat', 
    'maroni', 
    'martha wayne', 
    'mr. freeze', 
    'music meister', 
    'nightwing', 
    'oracle', 
    'penguin', 
    'poison ivy', 
    "ra's al ghul", 
    'red hood', 
    'red robin', 
    'renee montoya', 
    'riddler', 
    'robin', 
    'robin', 
    'scarecrow', 
    'solomon grundy', 
    'spoiler', 
    'talia al ghul', 
    'the dark knight', 
    'the night', 
    'thomas wayne', 
    'thorne', 
    'two-face', 
    'utility belt', 
    'vengeance', 
    'wayne manor', 
    'worlds greatest detective'


];
exports.extendedTerms = exports.commonTerms.concat([
    'professor pyg',
    'catman',
    'magpie',
    'deacon blackfire',
    'king tut',
    'egghead',
    'bluebird',
    'batwing',
    'rebreather',
]);
