exports.commonTerms = [
    'batman',
    'bruce wayne',
    'joker',
    'harley quinn',
    'gotham',
    'bat signal',
    'batmobile',
    'batwing',
    'batarang',
    'robin',
    'penguin',
    'killer croc',
    'solomon grundy',
    'bane',
    'poison ivy',
    'riddler',
    'mr. freeze',
    'catwoman',
    'mad hatter',
    'clock king',
    'two-face',
    'scarecrow',
    'black mask',
    'calendar man',
    'condiment king',
    'court of owls',
    'deathstroke',
    'firefly',
    'hush',
    'killer moth',
    'kite man',
    'talia al ghul',
    'ra&#039;s al ghul',
    'man-bat',
    'joe chill',
    'hugo strange',
    'deadshot',
    'anarky',
    'clayface',
    'kite-man',
    'arkham knight',
    'arkham asylum',
    'arkham',
    'thomas wayne',
    'martha wayne',
    'robin',
    'alfred pennyworth',
    'batgirl',
    'nightwing',
    'huntress',
    'black canary',
    'oracle',
    'spoiler',
    'batwoman',
    'red robin',
    'red hood',
    'azrael',
    'bat family',
    'justice league',
    'lazarus pit',
    'commissioner gordon',
    'gcpd',
    'falcone',
    'maroni',
    'thorne',
    'ace the bat-hound',
    'bat-mite',
    'lucius fox',
    'flying graysons',
    'blüdhaven',
    'burnside',
    'wayne manor',
    'worlds greatest detective',
    'batman beyond',
    'the dark knight',
    'brave and the bold',
    'bat shark repellent',
    'cape',
    'cowl',
    'vengeance',
    'the night',
    'I am batman',
    'caped crusader',
    'gadgets',
    'utility belt',
    'criminally insane',
    'justice',
    'bat-cave',
    'music meister',
    'renee montoya',
    'harvey bullock',


];
exports.extendedTerms = exports.commonTerms.concat([
    'professor pyg',
    'catman',
    'magpie',
    'deacon blackfire',
    'king tut',
    'egghead',
    'bluebird',
    'batwing',
    'rebreather',
]);
